openapi: 3.0.1
info:
  title: Bank Cards API
  version: "1.0.0"
  description: API для управления банковскими картами
paths:
  /api/auth/login:
    post:
      summary: Вход пользователя
      parameters:
        - in: query
          name: username
          required: true
          schema:
            type: string
        - in: query
          name: password
          required: true
          schema:
            type: string
      responses:
        "200":
          description: JWT токен
  /api/cards:
    get:
      summary: Получить все карты
      responses:
        "200":
          description: Список карт
    post:
      summary: Создать карту
      responses:
        "200":
          description: Карта создана
